package org.uvo.uvostore.service.settings;

// Public, unauthenticated read model for the storefront home page — merges the safe fields of
// StoreSettingsDto (branding/theme/home sections/benefits/contact/SEO) with the safe subset of
// GeneralSettingsDto (currency/tax/shipping). Deliberately excludes stripeSecretKey, posApiToken,
// posWebhookSecret and any other GeneralSettingsDto field that isn't meant to leave the server.
public record PublicStoreSettingsDto(
        String storeName,
        String storeDescription,
        String storeLogo,
        String storeFavicon,
        String primaryColor,
        String secondaryColor,
        String accentColor,
        String darkColor,
        boolean showHero,
        int heroAutoplaySpeed,
        boolean showCategories,
        String categoriesTitle,
        int categoriesLimit,
        boolean showNewProducts,
        String newProductsTitle,
        int newProductsLimit,
        int newProductsDays,
        boolean showFeaturedProducts,
        String featuredProductsTitle,
        int featuredProductsLimit,
        boolean showDeals,
        String dealsTitle,
        int dealsLimit,
        boolean showBenefits,
        String benefit1Icon,
        String benefit1Title,
        String benefit1Description,
        String benefit2Icon,
        String benefit2Title,
        String benefit2Description,
        String benefit3Icon,
        String benefit3Title,
        String benefit3Description,
        String benefit4Icon,
        String benefit4Title,
        String benefit4Description,
        String contactEmail,
        String contactPhone,
        String whatsappNumber,
        String facebookUrl,
        String instagramUrl,
        String twitterUrl,
        String tiktokUrl,
        String metaTitle,
        String metaDescription,
        String metaKeywords,
        String currency,
        String currencySymbol,
        String taxRate,
        boolean pricesIncludeTax,
        boolean shippingEnabled,
        String defaultShippingCost,
        boolean freeShippingEnabled,
        String freeShippingThreshold
) {
}
