CREATE TABLE store_settings (
    id BIGSERIAL PRIMARY KEY,
    store_name VARCHAR NOT NULL,
    store_logo VARCHAR,
    store_favicon VARCHAR,
    store_description TEXT,
    primary_color VARCHAR NOT NULL,
    secondary_color VARCHAR NOT NULL,
    accent_color VARCHAR NOT NULL,
    dark_color VARCHAR NOT NULL,
    show_hero BOOLEAN NOT NULL,
    hero_autoplay_speed INTEGER NOT NULL,
    show_categories BOOLEAN NOT NULL,
    categories_title VARCHAR,
    categories_limit INTEGER NOT NULL,
    show_new_products BOOLEAN NOT NULL,
    new_products_title VARCHAR,
    new_products_limit INTEGER NOT NULL,
    new_products_days INTEGER NOT NULL,
    show_featured_products BOOLEAN NOT NULL,
    featured_products_title VARCHAR,
    featured_products_limit INTEGER NOT NULL,
    show_deals BOOLEAN NOT NULL,
    deals_title VARCHAR,
    deals_limit INTEGER NOT NULL,
    show_benefits BOOLEAN NOT NULL,
    contact_email VARCHAR,
    contact_phone VARCHAR,
    whatsapp_number VARCHAR,
    facebook_url VARCHAR,
    instagram_url VARCHAR,
    twitter_url VARCHAR,
    tiktok_url VARCHAR,
    meta_title VARCHAR,
    meta_description TEXT,
    meta_keywords TEXT,
    benefit_1_icon VARCHAR,
    benefit_1_title VARCHAR,
    benefit_1_description TEXT,
    benefit_2_icon VARCHAR,
    benefit_2_title VARCHAR,
    benefit_2_description TEXT,
    benefit_3_icon VARCHAR,
    benefit_3_title VARCHAR,
    benefit_3_description TEXT,
    benefit_4_icon VARCHAR,
    benefit_4_title VARCHAR,
    benefit_4_description TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE settings (
    id BIGSERIAL PRIMARY KEY,
    key VARCHAR NOT NULL UNIQUE,
    value TEXT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE home_banners (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR NOT NULL,
    subtitle VARCHAR,
    description TEXT,
    image VARCHAR NOT NULL,
    mobile_image VARCHAR,
    cta_text VARCHAR NOT NULL,
    cta_link VARCHAR,
    cta_new_tab BOOLEAN NOT NULL,
    cta_secondary_text VARCHAR,
    cta_secondary_link VARCHAR,
    text_position VARCHAR NOT NULL,
    text_color VARCHAR NOT NULL,
    overlay_color VARCHAR,
    overlay_opacity INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
